import {
  onBoard1,
  onBoard2,
  onBoard3,
  notificationProfile1,
  notificationProfile2,
  notificationProfile3,
  notificationProfile4,
  favouriteBgImage,
  DetailSquareFoot,
  DetailDeceased,
  DetailDiversity,
  DetailGarageHome,
  DetailBed,
  DetailBathtub,
  profile,
} from '../Assests';

export const onBoardinData = [
  {
    id: 0,
    heading: 'Discover Your Dream Home at Your Fingertips.',
    image: onBoard1,
  },
  {
    id: 1,
    heading: 'Unlock the Door to Your Next Adventure.',
    image: onBoard2,
  },
  {
    id: 2,
    heading: 'Empower Your Home Search with Stound.',
    image: onBoard3,
  },
];

export const notificationData = [
  {
    id: 0,
    name: 'William James',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile1,
    time: '32 min ago',
  },
  {
    id: 1,
    name: 'Louis Frank',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile2,
    time: '32 min ago',
  },
  {
    id: 2,
    name: 'Liam Andrew',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile3,
    time: '32 min ago',
  },
  {
    id: 3,
    name: 'Benjamin Luis',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile4,
    time: '32 min ago',
  },
  {
    id: 4,
    name: 'Louis Frank',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile1,
    time: '32 min ago',
  },
  {
    id: 5,
    name: 'Liam Andrew',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile2,
    time: '32 min ago',
  },
  {
    id: 6,
    name: 'Benjamin Luis',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile3,
    time: '32 min ago',
  },
  {
    id: 7,
    name: 'Louis Frank',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile4,
    time: '32 min ago',
  },
  {
    id: 8,
    name: 'Liam Andrew',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile1,
    time: '32 min ago',
  },
  {
    id: 9,
    name: 'Louis Frank',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile2,
    time: '32 min ago',
  },
  {
    id: 10,
    name: 'Liam Andrew',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile3,
    time: '32 min ago',
  },
  {
    id: 11,
    name: 'Benjamin Luis',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile4,
    time: '32 min ago',
  },
  {
    id: 12,
    name: 'Louis Frank',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile1,
    time: '32 min ago',
  },
  {
    id: 13,
    name: 'Liam Andrew',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile2,
    time: '32 min ago',
  },
];

export const favouriteData = [
  {
    id: 1,
    backgroundImage: favouriteBgImage,
    title: 'Chessington Kanass',
    locationText: '1050 Old Nichols Rd Islandia.',
    price: '$1500',
    duration: 'month',
    baths: '3 Baths',
    beds: '4 Beds',
    size: '120 sqft',
  },
  {
    id: 2,
    backgroundImage: favouriteBgImage,
    title: 'Chessington Kanass',
    locationText: '1050 Old Nichols Rd Islandia.',
    price: '$1500',
    duration: 'month',
    baths: '3 Baths',
    beds: '4 Beds',
    size: '120 sqft',
  },
  {
    id: 3,
    backgroundImage: favouriteBgImage,
    title: 'Chessington Kanass',
    locationText: '1050 Old Nichols Rd Islandia.',
    price: '$1500',
    duration: 'month',
    baths: '3 Baths',
    beds: '4 Beds',
    size: '120 sqft',
  },
  {
    id: 4,
    backgroundImage: favouriteBgImage,
    title: 'Chessington Kanass',
    locationText: '1050 Old Nichols Rd Islandia.',
    price: '$1500',
    duration: 'month',
    baths: '3 Baths',
    beds: '4 Beds',
    size: '120 sqft',
  },
  {
    id: 5,
    backgroundImage: favouriteBgImage,
    title: 'Chessington Kanass',
    locationText: '1050 Old Nichols Rd Islandia.',
    price: '$1500',
    duration: 'month',
    baths: '3 Baths',
    beds: '4 Beds',
    size: '120 sqft',
  },
];

export const ChatData = [
  {
    id: 0,
    name: 'William James',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile1,
    time: '4:32 PM',
    messages: '2',
  },
  {
    id: 1,
    name: 'Louis Frank',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile2,
    time: '4:32 PM',
  },
  {
    id: 2,
    name: 'Liam Andrew',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile3,
    time: '4:32 PM',
    messages: '5',
  },
  {
    id: 3,
    name: 'Benjamin Luis',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile4,
    time: '4:32 PM',
  },
  {
    id: 4,
    name: 'Louis Frank',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile1,
    time: '4:32 PM',
    messages: '1',
  },
  {
    id: 5,
    name: 'Liam Andrew',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile2,
    time: '4:32 PM',
  },
  {
    id: 6,
    name: 'Benjamin Luis',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile3,
    time: '4:32 PM',
    messages: '3',
  },
  {
    id: 7,
    name: 'Louis Frank',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile4,
    time: '4:32 PM',
  },
  {
    id: 8,
    name: 'Liam Andrew',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile1,
    time: '4:32 PM',
    messages: '6',
  },
  {
    id: 9,
    name: 'Louis Frank',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile2,
    time: '4:32 PM',
  },
  {
    id: 10,
    name: 'Liam Andrew',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile3,
    time: '4:32 PM',
    messages: '5',
  },
  {
    id: 11,
    name: 'Benjamin Luis',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile4,
    time: '4:32 PM',
  },
  {
    id: 12,
    name: 'Louis Frank',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile1,
    time: '4:32 PM',
    messages: '2',
  },
  {
    id: 13,
    name: 'Liam Andrew',
    description: 'Interested in your property and want to talk.',
    image: notificationProfile2,
    time: '4:32 PM',
  },
];

export const homeCardData = [
  'DO',
  'MORE',
  'OF',
  'WHAT',
  'MAKES',
  'YOU',
  'HAPPY',
  'DO',
  'MORE',
  'OF',
  'WHAT',
  'MAKES',
  'YOU',
  'HAPPY',
  'DO',
  'MORE',
  'OF',
  'WHAT',
  'MAKES',
  'YOU',
  'HAPPY',
  'DO',
  'MORE',
  'OF',
  'WHAT',
  'MAKES',
  'YOU',
  'HAPPY',
];
export const msgs = [
  {
    user: 'sender',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dummy text of the printing.',
    time: '3:15 PM',
  },
  {
    user: 'reciever',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dumm',
    time: '3:15 PM',
  },
  {
    user: 'sender',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dummy text of the printing. Lorem Ipsum is simply dummy text of the printing.',
    time: '3:15 PM',
  },
  {
    user: 'reciever',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dummy text of the printing. Lorem Ipsum is simply dummy text of the printing. Lorem Ipsum is simply dummy text of the printing lines in.',
    time: '3:15 PM',
  },
  {
    user: 'sender',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dummy text of the printing.',
    time: '3:15 PM',
  },
  {
    user: 'reciever',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dumm',
    time: '3:15 PM',
  },
  {
    user: 'reciever',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dummy text of the printing. Lorem Ipsum is simply dummy text of the printing. Lorem Ipsum is simply dummy text of the printing lines in.',
    time: '3:15 PM',
  },
  {
    user: 'sender',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dummy text of the printing.',
    time: '3:15 PM',
  },
  {
    user: 'reciever',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dumm',
    time: '3:15 PM',
  },
];
export const detailsImages = [
  'https://images.pexels.com/photos/12629063/pexels-photo-12629063.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  'https://images.pexels.com/photos/12629063/pexels-photo-12629063.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  'https://images.pexels.com/photos/12629063/pexels-photo-12629063.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  'https://images.pexels.com/photos/12629063/pexels-photo-12629063.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  'https://images.pexels.com/photos/12629063/pexels-photo-12629063.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  'https://images.pexels.com/photos/12629063/pexels-photo-12629063.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  'https://images.pexels.com/photos/12629063/pexels-photo-12629063.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  'https://images.pexels.com/photos/12629063/pexels-photo-12629063.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  'https://images.pexels.com/photos/12629063/pexels-photo-12629063.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  'https://images.pexels.com/photos/12629063/pexels-photo-12629063.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  'https://images.pexels.com/photos/12629063/pexels-photo-12629063.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  'https://images.pexels.com/photos/12629063/pexels-photo-12629063.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
];

export const PackageDetailData = {
  title: 'Chessington Kanass',
  forRent: 'For Rent',
  forSale: 'For Sell',
  location: '1050 Old Nichols Rd Islandia, NY 11749',
  time: '3:15 PM',
  tags: [
    {
      icon: DetailBathtub,
      text: '3 Baths',
    },
    {
      icon: DetailBed,
      text: '4 Beds',
    },
    ,
    {
      icon: DetailGarageHome,
      text: 'Parking',
    },
    ,
    {
      icon: DetailDiversity,
      text: 'Friendly',
    },
    ,
    {
      icon: DetailDeceased,
      text: 'Garden',
    },
    ,
    {
      icon: DetailSquareFoot,
      text: '120 sqft',
    },
  ],
  prifilePicture: profile,
  userName: 'Jhon Doe',
  userEmail: 'jhondoe@gmail.com',
  price: '4,500',
};
